-- PRODUCT 테이블과 OFFLINE_SALE 테이블
-- PRODUCT_ID 기준으로 조인을침 
-- 
SELECT  P.PRODUCT_CODE  , SUM(P.PRICE *O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC , P.PRODUCT_CODE ASC