-- 코드를 입력하세요
SELECT R.FOOD_TYPE	, R.REST_ID	 , R.REST_NAME	, R.FAVORITES
FROM REST_INFO R 
JOIN
(SELECT FOOD_TYPE,
         MAX(FAVORITES) AS MAX_FAVORITES
FROM
         REST_INFO
   GROUP BY
         FOOD_TYPE
)max_favorites
ON
    R.FOOD_TYPE = max_favorites.FOOD_TYPE
    AND R.FAVORITES = max_favorites.MAX_FAVORITES
ORDER BY R.FOOD_TYPE DESC