-- 코드를 입력하세요
# SELECT *
# FROM FIRST_HALF 
# WHERE TOTAL_ORDER >3000


# SELECT FLAVOR
# FROM ICECREAM_INFO
# WHERE INGREDIENT_TYPE = 'fruit_based' 


SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I  ON F.FLAVOR = I.FLAVOR
WHERE  I.INGREDIENT_TYPE = 'fruit_based'  AND F.TOTAL_ORDER > 3000
ORDER BY F.TOTAL_ORDER DESC;
