-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
ON C.CAR_ID= R.CAR_ID
WHERE C.CAR_TYPE ='세단' AND R.START_DATE LIKE "2022-10-%"
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC