-- 코드를 AVG_SAL
SELECT  E.DEPT_ID ,	D.DEPT_NAME_EN , ROUND(SUM(E.SAL)/COUNT(E.EMP_NAME)) AS AVG_SAL

FROM HR_DEPARTMENT D 
JOIN HR_EMPLOYEES  E  ON D.DEPT_ID= E.DEPT_ID

GROUP BY D.DEPT_NAME_EN ,E.DEPT_ID
ORDER BY AVG_SAL DESC