SELECT 
    F.CATEGORY, 
    F.PRICE AS MAX_PRICE, 
    F.PRODUCT_NAME
FROM 
    FOOD_PRODUCT F
WHERE 
    F.CATEGORY IN ('과자', '국', '김치', '식용유') AND
    F.PRICE = (
        SELECT MAX(F2.PRICE)
        FROM FOOD_PRODUCT F2
        WHERE F2.CATEGORY = F.CATEGORY
    )
ORDER BY 
    F.PRICE DESC;
